name: Build and Deploy Website TicketMaster

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Build application
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        run: npm run build
      - name: Test application
        run: npm test
      - name: echo-ing
        run: echo "Running on ${{ github.event.pull_request.merged }} and ${{ github.event.pull_request.base.ref }} -- ${{ github.ref }}"
  deploy:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echo-ing
        run: echo "--- Running on ${{ github.event.pull_request.merged }} and ${{ github.event.pull_request.base.ref }} -- ${{ github.ref }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install modules
        run: npm i
      - name: Build application
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_API_SQL: ${{ secrets.VITE_API_SQL }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
      - name: Deploy to S3
        run: aws s3 sync ./build/ s3://${{ secrets.BUCKET_NAME }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
      - name: End deploy
        run: echo "***** Deploy successfully *****"
